version: '3.8'

services:
  # ------------------------------
  # Zookeeper for Kafka A (Business)
  # ------------------------------
  zookeeper-business:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-business:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper-business
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-business:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ------------------------------
  # Zookeeper for Kafka B (Logging)
  # ------------------------------
  zookeeper-logs:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000

  kafka-logs:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper-logs
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-logs:2182
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ------------------------------
  # OpenTelemetry Collector
  # ------------------------------
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    depends_on:
      - kafka-logs

  # ------------------------------
  # Kafka UI for visibility
  # ------------------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: business
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-business:9092
      KAFKA_CLUSTERS_1_NAME: logging
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka-logs:9093
