receivers:
  otlp:
    protocols:
      grpc:

exporters:
  kafka:
    brokers:
      - "kafka:9092"
    topic: "otel-logs"
    encoding: "otlp_proto"

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [kafka]