{{- range .Values.images }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-app.fullname" $ }}-{{ .name }}
  labels:
    {{- include "my-helm-app.labels" $ | nindent 4 }}
    component: {{ .name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "my-helm-app.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    component: {{ .name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  type: ClusterIP
---
{{- end }}
